on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

env:
  DEVTOOLS_COLOR: always

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        package:
          - gnome-shell-extension-ddterm
          - gnome-shell-extension-ddterm-git
        check:
          - check
          - nocheck

    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/archlinux/archlinux:base-devel
      options: --privileged --tmpfs /run

    steps:
    - run: sed -i '/^NoExtract/d' /etc/pacman.conf
    - run: echo "$REPO_CONFIG" >> /etc/pacman.conf
      env:
        REPO_CONFIG: |
          [ddterm]
          SigLevel = Never
          Server = https://ddterm.github.io/aur

    - run: pacman -Syu --noconfirm --noprogressbar --color=always devtools
    - run: systemd-machine-id-setup
    - run: useradd -m builduser
    - run: echo "$GITHUB_WORKSPACE/.github/bin" >> "$GITHUB_PATH"

    - uses: actions/checkout@v4
    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"
    - run: chown -R builduser .

    - run: mkarchroot -C /etc/pacman.conf -M /etc/makepkg.conf /var/tmp/root base-devel
    - run: makechrootpkg -r /var/tmp -c -n -C -U builduser -- --${{ matrix.check }}
      working-directory: ${{ matrix.package }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.package }}-${{ matrix.check }}
        path: |
          ${{ matrix.package }}/*.pkg.tar.*
          ${{ matrix.package }}/*.log
        if-no-files-found: error
      if: always()

  srcinfo:
    strategy:
      fail-fast: false
      matrix:
        package:
          - gnome-shell-extension-ddterm
          - gnome-shell-extension-ddterm-git

    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/archlinux/archlinux:base

    steps:
    - run: pacman -Syu --noconfirm --noprogressbar --color=always git sudo
    - run: useradd -m builduser

    - uses: actions/checkout@v4
    - run: git config --global --replace-all safe.directory "$GITHUB_WORKSPACE"
    - run: chown -R builduser .

    - run: sudo -u builduser makepkg --printsrcinfo >.SRCINFO
      working-directory: ${{ matrix.package }}

    - run: git diff --exit-code .SRCINFO
      working-directory: ${{ matrix.package }}

  repo:
    needs: package
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/archlinux/archlinux:base

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: repo
          pattern: '*-nocheck'
          merge-multiple: true

      - run: rm *.log
        working-directory: repo

      - run: repo-add ddterm.db.tar.zst *.pkg.tar.*
        working-directory: repo

      - uses: actions/upload-pages-artifact@v3
        with:
          path: repo
