name: push

concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - renovate/**
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
